# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a4ee28f73604e5854660ae155540cb81db4883a3de40dec55aaf12369af8499c3615dbffe79e728f389c140eadda4fd47b91eb7208693d5209dbc7de672ec12

test:
  secret_key_base: bc4ae5fd8e990275378959e123a4dbfd40f7a36275c5524c4c6ccf04075752916f79818cafec95db714362f57af452f62a6829a4b7c016db6698037e4b9d1c1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
